version: "3.6"

services:
  scraper:
    image: "skynetlabs/content-record-scraper"
    container_name: content-record-scraper
    depends_on:
      - "mongo"
    environment:
      CR_DATA_DOMAIN: "crqa.hns"
      DEBUG_ENABLED: "false"
      MONGO_CONNECTION_STRING: "mongodb://mongo:27017"
  mongo:
    image: "bitnami/mongodb:4.2"
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
